# Generated by Django 3.1.7 on 2021-11-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211117_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='communityPosts',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
